import { useState } from "react";
import { Search, ChevronDown, ChevronUp } from "lucide-react";

interface GlossaryItem {
  term: string;
  definition: string;
  where: string;
  example: string;
}

const glossary: GlossaryItem[] = [
  { term: "CPM", definition: "Cost per 1,000 impressions.", where: "Buying and reporting dashboards.", example: "A $2 CPM means you pay $2 for every 1,000 ad views." },
  { term: "CPC", definition: "Cost per click on an ad.", where: "Performance reports and bid settings.", example: "$0.30 CPC on a search campaign." },
  { term: "CPA", definition: "Cost per acquisition or conversion.", where: "ROI/ROAS analysis.", example: "If CPA is $10 and LTV is $50, the campaign is profitable." },
  { term: "CR", definition: "Conversion rate — ratio of conversions to clicks (or impressions).", where: "Campaign performance tables.", example: "200 clicks, 10 conversions → 5% CR." },
  { term: "ROAS", definition: "Return on ad spend — revenue divided by ad cost.", where: "Budget allocation and executive reports.", example: "Spent $100, earned $400 → ROAS = 4x." },
  { term: "RTB", definition: "Real-time bidding — an auction for each ad impression.", where: "Programmatic media buying.", example: "An RTB auction completes in ~100ms." },
  { term: "DSP", definition: "Demand-side platform — where advertisers buy inventory.", where: "Campaign setup and management.", example: "DV360, The Trade Desk, MediaMath." },
  { term: "SSP", definition: "Supply-side platform — where publishers sell inventory.", where: "Publisher-side reporting.", example: "Google Ad Manager, Magnite, PubMatic." },
  { term: "Ad Exchange", definition: "A marketplace connecting DSPs and SSPs.", where: "Supply chain diagrams.", example: "Google AdX is one of the largest exchanges." },
  { term: "Bid", definition: "The price offered for an impression in an auction.", where: "Bid strategies and optimization.", example: "Setting a max bid of $3 CPM." },
  { term: "Win Rate", definition: "Percentage of bids that win the auction.", where: "DSP reporting dashboards.", example: "15% win rate means 15 of 100 bids succeed." },
  { term: "Impression", definition: "One instance of an ad being served/displayed.", where: "Virtually every report.", example: "A page load with a banner = 1 impression." },
  { term: "Click", definition: "A user interaction with an ad.", where: "CTR reports and attribution.", example: "A click-through to the advertiser's landing page." },
  { term: "Conversion", definition: "A desired action (purchase, signup, install).", where: "Attribution and performance tracking.", example: "User installs the app after clicking an ad." },
  { term: "Postback", definition: "A server-to-server notification confirming a conversion.", where: "Tracking and attribution systems.", example: "MMP fires a postback to DSP upon install." },
  { term: "Attribution Window", definition: "Time frame in which a conversion is credited to an ad.", where: "Attribution settings.", example: "7-day click, 1-day view attribution window." },
  { term: "Frequency Cap", definition: "Max number of times a user sees the same ad.", where: "Campaign targeting settings.", example: "Cap of 3 impressions per user per day." },
  { term: "Creative", definition: "The actual ad asset (image, video, HTML).", where: "Ad setup and A/B testing.", example: "A 300×250 banner creative." },
  { term: "Placement", definition: "A specific location on a publisher's page/app.", where: "Inventory targeting.", example: "Top-of-page leaderboard on news site." },
  { term: "Deal ID", definition: "A unique identifier for a private marketplace deal.", where: "PMP and direct deals setup.", example: "Deal ID shared between buyer and seller." },
  { term: "PMP", definition: "Private marketplace — invitation-only auction.", where: "Premium inventory buying.", example: "A PMP deal with a tier-1 publisher." },
  { term: "Brand Safety", definition: "Measures ensuring ads don't appear near harmful content.", where: "Quality and compliance settings.", example: "Blocking ads on pages with violent content." },
  { term: "Fraud", definition: "Invalid traffic generated by bots or deceptive practices.", where: "Quality reports and IVT filters.", example: "Bot-generated clicks inflating CTR." },
  { term: "Discrepancy", definition: "Difference in numbers between two reporting systems.", where: "Reconciliation between DSP and SSP.", example: "DSP shows 10k clicks, SSP shows 8k." },
];

export default function Glossary() {
  const [search, setSearch] = useState("");
  const [expanded, setExpanded] = useState<string | null>(null);

  const filtered = glossary.filter(
    (g) =>
      g.term.toLowerCase().includes(search.toLowerCase()) ||
      g.definition.toLowerCase().includes(search.toLowerCase())
  );

  return (
    <section id="glossary" className="py-20 md:py-24">
      <div className="container mx-auto px-4">
        <div className="mb-8 scroll-reveal">
          <h2 className="text-3xl md:text-4xl font-bold text-foreground mb-3">Programmatic glossary</h2>
          <p className="text-muted-foreground text-lg max-w-xl">
            Short definitions + where you'll see it in real work.
          </p>
        </div>

        <div className="scroll-reveal relative mb-10 max-w-md">
          <Search size={18} className="absolute left-3 top-1/2 -translate-y-1/2 text-muted-foreground" />
          <input
            type="text"
            placeholder="Search a term (e.g., CPM, SSP, discrepancy…)"
            value={search}
            onChange={(e) => setSearch(e.target.value)}
            className="w-full pl-10 pr-4 py-3 rounded-xl border border-border bg-card text-foreground placeholder:text-muted-foreground focus:outline-none focus:ring-2 focus:ring-primary/30 transition"
          />
        </div>

        <div className="grid md:grid-cols-2 lg:grid-cols-3 gap-4">
          {filtered.map((g, i) => {
            const isOpen = expanded === g.term;
            return (
              <div
                key={g.term}
                className="scroll-reveal bg-card border border-border rounded-xl overflow-hidden card-hover cursor-pointer"
                style={{ transitionDelay: `${(i % 6) * 40}ms` }}
                onClick={() => setExpanded(isOpen ? null : g.term)}
              >
                <div className="p-4">
                  <div className="flex items-center justify-between mb-1">
                    <h4 className="font-semibold text-foreground">{g.term}</h4>
                    {isOpen ? <ChevronUp size={16} className="text-muted-foreground" /> : <ChevronDown size={16} className="text-muted-foreground" />}
                  </div>
                  <p className="text-sm text-muted-foreground">{g.definition}</p>
                  <p className="text-xs text-muted-foreground/70 mt-1">Where: {g.where}</p>
                </div>
                {isOpen && (
                  <div className="border-t border-border bg-muted/30 p-4">
                    <p className="text-sm text-foreground">
                      <span className="font-medium">Example:</span> {g.example}
                    </p>
                  </div>
                )}
              </div>
            );
          })}
        </div>
      </div>
    </section>
  );
}
